esphome:
  name: fingerprint-doorbell
  friendly_name: Fingerprint Doorbell
  includes:
    - fingerprint_pairing.h
  on_boot:
    priority: -100
    then:
      - logger.log: "Fingerprint Doorbell started"
      - lambda: |-
          // Check pairing on boot
          id(pairing_component)->check_pairing();

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FingerprintDoorbell-Config"
    password: "12345678"

captive_portal:

# Web server for management
web_server:
  port: 80

# MQTT (optional - Home Assistant integration via API is preferred)
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: fingerprintDoorbell
  birth_message:
    topic: fingerprintDoorbell/status
    payload: online
  will_message:
    topic: fingerprintDoorbell/status
    payload: offline

# Preferences for storing pairing code
preferences:
  flash_write_interval: 1min

# UART for fingerprint sensor
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 57600

# Custom component for sensor pairing
custom_component:
  - lambda: |-
      auto pairing = new FingerprintPairing(id(uart_bus));
      App.register_component(pairing);
      return {pairing};
    components:
      - id: pairing_component

# Fingerprint sensor (Grow R503)
fingerprint_grow:
  id: fingerprint_reader
  sensing_pin: GPIO5  # Touch ring detection pin
  password: 0x00000000
  new_password: 0x00000000
  on_finger_scan_matched:
    - lambda: |-
        // Check pairing before allowing matched fingerprint
        if (!id(pairing_valid).state) {
          ESP_LOGW("fingerprint", "Security issue! Pairing invalid - match ignored!");
          id(pairing_warning).publish_state("SECURITY WARNING: Sensor pairing invalid! This could be an attack. Do re-pairing in settings.");
          return;
        }
    - logger.log:
        format: "Fingerprint matched: ID %d with confidence %d"
        args: ['id', 'confidence']
    - mqtt.publish:
        topic: fingerprintDoorbell/matchId
        payload: !lambda 'return to_string(id);'
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchName
        payload: !lambda |-
          // Get name from preferences based on ID
          char key[20];
          sprintf(key, "finger_name_%d", id);
          auto name = id(global_prefs).get<std::string>(key);
          return name.value_or("Unknown");
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchConfidence
        payload: !lambda 'return to_string(confidence);'
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/ring
        payload: "off"
        retain: false
    - delay: 3s
    - mqtt.publish:
        topic: fingerprintDoorbell/matchId
        payload: "-1"
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchName
        payload: ""
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchConfidence
        payload: "-1"
        retain: false
  
  on_finger_scan_unmatched:
    - logger.log: "Fingerprint not matched - ringing doorbell"
    - switch.turn_on: doorbell_relay
    - mqtt.publish:
        topic: fingerprintDoorbell/ring
        payload: "on"
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchId
        payload: "-1"
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchName
        payload: ""
        retain: false
    - mqtt.publish:
        topic: fingerprintDoorbell/matchConfidence
        payload: "-1"
        retain: false
    - delay: 1s
    - switch.turn_off: doorbell_relay
    - mqtt.publish:
        topic: fingerprintDoorbell/ring
        payload: "off"
        retain: false
  
  on_enrollment_scan:
    - logger.log:
        format: "Enrollment scan %d/6 captured"
        args: ['scan_num']
  
  on_enrollment_done:
    - logger.log:
        format: "Fingerprint enrolled with ID %d"
        args: ['finger_id']
  
  on_enrollment_failed:
    - logger.log:
        format: "Enrollment failed with error code %d"
        args: ['error_code']

# Binary sensor for touch ring detection
binary_sensor:
  - platform: gpio
    id: touch_ring_sensor
    pin:
      number: GPIO5
      mode: INPUT_PULLDOWN
    name: "Touch Ring"
    filters:
      - delayed_on: 10ms
  
  # Pairing valid status
  - platform: template
    id: pairing_valid
    name: "Sensor Pairing Valid"
    icon: "mdi:shield-check"
    device_class: safety
  
  # Connection status
  - platform: status
    name: "Status"

# Switch for doorbell relay/output
switch:
  - platform: gpio
    id: doorbell_relay
    pin: GPIO19
    name: "Doorbell Output"
    restore_mode: ALWAYS_OFF
  
  # Switch to ignore touch ring (for rainy weather)
  - platform: template
    id: ignore_touch_ring
    name: "Ignore Touch Ring"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Touch ring detection disabled (rain mode)"
    on_turn_off:
      - logger.log: "Touch ring detection enabled"

# Sensors
sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "Fingerprint Count"
    status:
      name: "Sensor Status"
    capacity:
      name: "Sensor Capacity"
    security_level:
      name: "Security Level"
    last_finger_id:
      id: last_finger_id
      name: "Last Finger ID"
    last_confidence:
      id: last_confidence
      name: "Last Confidence"
  
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  
  - platform: uptime
    name: "Uptime"

# Text sensors
text_sensor:
  - platform: template
    id: pairing_warning
    name: "Security Warning"
    icon: "mdi:alert"
    
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"

# Globals for preferences
globals:
  - id: global_prefs
    type: ESPPreferenceObject
    restore_value: yes

# Buttons for actions
button:
  - platform: restart
    name: "Restart"
  
  - platform: template
    name: "Start Enrollment"
    id: start_enrollment
    on_press:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return id(enrollment_finger_id).state;'
          num_scans: 6
  
  - platform: template
    name: "Cancel Enrollment"
    on_press:
      - fingerprint_grow.cancel_enroll:
  
  - platform: template
    name: "Delete All Fingerprints"
    on_press:
      - fingerprint_grow.delete_all:
  
  - platform: template
    name: "Pair New Sensor"
    icon: "mdi:shield-link-variant"
    on_press:
      - logger.log: "Starting sensor pairing..."
      - lambda: |-
          id(pairing_component)->do_pairing();
  
  - platform: template
    name: "Check Pairing Status"
    icon: "mdi:shield-search"
    on_press:
      - lambda: |-
          id(pairing_component)->check_pairing();
  
  - platform: template
    name: "Delete Selected Fingerprint"
    on_press:
      - fingerprint_grow.delete:
          finger_id: !lambda 'return atoi(id(delete_finger_id).state.c_str());'

# Number input for enrollment
number:
  - platform: template
    id: enrollment_finger_id
    name: "Enrollment Finger ID"
    optimistic: true
    min_value: 1
    max_value: 200
    step: 1
    initial_value: 1
    mode: box

# Select for deleting specific fingerprint
select:
  - platform: template
    id: delete_finger_id
    name: "Delete Finger ID"
    optimistic: true
    options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "10"
      - "15"
      - "20"
      # Add more as needed
    initial_option: "1"

# MQTT subscribe for ignore touch ring control
mqtt:
  on_message:
    - topic: fingerprintDoorbell/ignoreTouchRing
      then:
        - lambda: |-
            if (x == "on") {
              id(ignore_touch_ring).turn_on();
            } else if (x == "off") {
              id(ignore_touch_ring).turn_off();
            }
